### ISSUE TITLE
Search for Duplicate/Similar Photos

### ISSUE THREAD

**Issue by cabouezzi** [cabouezzi/PhotoManagement#7]
**User story**
I want to detect duplicate photos and remove them to free up space. I want to be able to detect photos that are very similar to each other and choose one (or all) to keep.

**Description**
A function to scan and detect duplicates/almost identical photos and give users the option to keep or remove them (one by one).

**Acceptance criteria**

- [ ] Be able to scan the whole folder
- [ ] Detect duplicates or almost identical photos
- [ ] Show their properties such as date added, date modified, image size, image resolution, etc.
- [ ] Be able to preview the photos and compare
- [ ] Users can choose to keep or remove the photos

**Dependencies**
#4

**Comment by lemanhstudy4111** [comment]
**User story**
I want to detect duplicate photos and remove them to free up space. I want to be able to detect photos that are very similar to each other and choose one (or all) to keep.
**Description**
A function to scan and detect duplicates/almost identical photos and give users the option to keep or remove them (one by one).
**Acceptance criteria**

- [ ] Be able to scan the whole folder
- [ ] Detect duplicates or almost identical photos
- [ ] Show their properties such as date added, date modified, image size, image resolution, etc.
- [ ] Be able to preview the photos and compare
- [ ] Users can choose to keep or remove the photos

**Dependencies**
#4
