### ISSUE TITLE
Edit Photos

### ISSUE THREAD

**Issue by cabouezzi** [cabouezzi/PhotoManagement#8]
**User story**
I want to be able to edit the photos I uploaded in the photo management app.

**Description**
Provide a function to adjust:
- Contrast
- Saturation
- brightness
- Turn image black and white

**Acceptance criteria**
- [ ]  Takes in a photo
- [ ]  UI provided options to adjust contrast, saturation, brightness, make image black and white
- [ ]  Image effect is as expected
- [ ]  User will be able to get the photo (via download, the photo will be added to the folder, etc.)

**Dependencies**
None

**Comment by lemanhstudy4111** [comment]
**User story**
I want to be able to edit the photos I uploaded in the photo management app
**Description**
Provide a function to adjust:
- Contrast
- Saturation
- brightness
- Turn image black and white
**Acceptance criteria**
- [ ]  Takes in a photo
- [ ]  UI provided options to adjust contrast, saturation, brightness, make image black and white
- [ ]  Image effect is as expected
- [ ]  User will be able to get the photo (via download, the photo will be added to the folder, etc.)
**Dependencies**
None

**Comment by Lexisescro** [comment]
Convert the code from CS373 to python code
