### ISSUE TITLE
Setup Docker/Elasticsearch server

### ISSUE THREAD

**Issue by jschwab012** [cabouezzi/PhotoManagement#9]
User Story
(As a [type of user], I want [goal] so that [reason].)

Description
(Provide a detailed explanation of the issue or feature request. Include the problem it aims to solve.)

Acceptance Criteria
(List the conditions that must be met for the issue to be considered complete.)

[ ] Criterion 1
[ ] Criterion 2
[ ] Criterion 3

Tasks
(Break down the work into actionable tasks if applicable.)

[ ] Task 1
[ ] Task 2
[ ] Task 3

Dependencies
#4 

Impact
(Describe how this will impact the project or user experience.)

Additional Notes
(Any other relevant information or context, such as related documentation or design mockups.)

**Comment by cabouezzi** [comment]
I don't think this is a task for development, it's just that it's a requirement for our system. We could just give a link to [this page](https://www.elastic.co/guide/en/elasticsearch/reference/current/run-elasticsearch-locally.html) in a readme or something for setup instructions.
